version: "3.7"

networks:
  kong-net:
    name: kong-net
    driver: bridge
   

services:

  service-1:
    image: wesleywillians/kong-service:latest
    environment:
      PORT: ":8081"
      CONTENT: "<h1>Service A</h1>"
    networks:
      - kong-net
    ports:
      - 8081:8081

  service-2:
    image: wesleywillians/kong-service:latest
    environment:
      PORT: ":8082"
      CONTENT: "<h1>Service b</h1>"
    networks:
      - kong-net
    ports:
      - 8082:8082

  service-3:
    image: wesleywillians/kong-service:latest
    environment:
      PORT: ":8083"
      CONTENT: "<h1>Service C</h1>"
    networks:
      - kong-net
    ports:
      - 8083:8083

  service-4:
    image: wesleywillians/kong-service:latest
    environment:
      PORT: ":8084"
      CONTENT: "<h1>Service D</h1>"
    networks:
      - kong-net
    ports:
      - 8084:8084

  service-5:
    image: wesleywillians/kong-service:latest
    environment:
      PORT: ":8085"
      CONTENT: "<h1>Service E</h1>"
    networks:
      - kong-net
    ports:
      - 8085:8085

  service-6:
    image: wesleywillians/kong-service:latest
    environment:
      PORT: ":8086"
      CONTENT: "<h1>Service F</h1>"
    networks:
      - kong-net
    ports:
      - 8086:8086

  service-7:
    image: wesleywillians/kong-service:latest
    environment:
      PORT: ":8087"
      CONTENT: "<h1>Service G</h1>"
    networks:
      - kong-net
    ports:
      - 8087:8087

  service-8:
    image: wesleywillians/kong-service:latest
    environment:
      PORT: ":8088"
      CONTENT: "<h1>Service H</h1>"
    networks:
      - kong-net
    ports:
      - 8088:8088

  service-9:
    image: wesleywillians/kong-service:latest
    environment:
      PORT: ":8089"
      CONTENT: "<h1>Service J</h1>"
    networks:
      - kong-net
    ports:
      - 8089:8089